### ISSUE TITLE
关于订阅提示信息的问题

### ISSUE THREAD

**Issue by tpof314** [lepture/flask-weixin#13]
你好！我的微信公众号目前需要用到一些微信方面的API，用了您的这个库，觉得非常非常方便。不过现在有一个问题，新用户订阅我们微信号的时候，我们希望能够有一段文字提示。请问这个库里面有没有提供这样的功能？

**Comment by tonyseek** [comment]
Docs: [关注/取消关注事件](http://mp.weixin.qq.com/wiki/2/5baf56ce4947d35003b86a9805634b1e.html#.E5.85.B3.E6.B3.A8.2F.E5.8F.96.E6.B6.88.E5.85.B3.E6.B3.A8.E4.BA.8B.E4.BB.B6)

``` python
@weixin.register(type='event', event='subscribe')
def welcome(sender, receiver, **kwargs):
    return weixin.reply(sender, sender=receiver, content='welcome')
```

**Comment by tpof314** [comment]
哦！！
那如果是普通的text消息的话，是不是直接这样处理就可以了？
 
@weixin.register(type='text')
def welcome(sender, receiver, **kwargs):
    return weixin.reply(sender, sender=receiver, content='xxxxxxxxxxxxx')

**Comment by lepture** [comment]
@tonyseek 写一点文档吧。其实不需要调用 `weixin.reply`

```python
@weixin.register(type='event', event='subscribe')
def welcome(**kwargs):
    return 'welcome'
```

**Comment by tonyseek** [comment]
好，周末写
